/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SolicitudCursoRouteImport } from './routes/solicitud-curso'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecuperarPasswordRouteImport } from './routes/recuperar-password'
import { Route as ProgramasRouteImport } from './routes/programas'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as DocentesRouteImport } from './routes/docentes'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AccederRouteImport } from './routes/acceder'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramasIndexRouteImport } from './routes/programas.index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as VerificarNumeroRouteImport } from './routes/verificar.$numero'
import { Route as ProgramasSlugRouteImport } from './routes/programas.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedEstudianteRouteImport } from './routes/_authenticated/estudiante'
import { Route as AuthenticatedDocenteRouteImport } from './routes/_authenticated/docente'
import { Route as AuthenticatedCertificadosRouteImport } from './routes/_authenticated/certificados'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMisCursosIndexRouteImport } from './routes/_authenticated/mis-cursos.index'
import { Route as AuthenticatedEstudianteIndexRouteImport } from './routes/_authenticated/estudiante.index'
import { Route as AuthenticatedDocenteIndexRouteImport } from './routes/_authenticated/docente.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicZoomWebhookRouteImport } from './routes/api/public/zoom-webhook'
import { Route as ApiPublicCourseRequestRouteImport } from './routes/api/public/course-request'
import { Route as ApiPublicBalanceActivoWebhookRouteImport } from './routes/api/public/balance-activo-webhook'
import { Route as AuthenticatedMisCursosSlugRouteImport } from './routes/_authenticated/mis-cursos.$slug'
import { Route as AuthenticatedEstudianteInstructivoRouteImport } from './routes/_authenticated/estudiante.instructivo'
import { Route as AuthenticatedEstudianteFacturacionRouteImport } from './routes/_authenticated/estudiante.facturacion'
import { Route as AuthenticatedEstudianteEvaluacionesRouteImport } from './routes/_authenticated/estudiante.evaluaciones'
import { Route as AuthenticatedEstudianteCuentaRouteImport } from './routes/_authenticated/estudiante.cuenta'
import { Route as AuthenticatedDocenteLeccionesRouteImport } from './routes/_authenticated/docente.lecciones'
import { Route as AuthenticatedDocenteInstructivoRouteImport } from './routes/_authenticated/docente.instructivo'
import { Route as AuthenticatedDocenteGruposRouteImport } from './routes/_authenticated/docente.grupos'
import { Route as AuthenticatedDocenteEvaluacionesRouteImport } from './routes/_authenticated/docente.evaluaciones'
import { Route as AuthenticatedDocenteCursosRouteImport } from './routes/_authenticated/docente.cursos'
import { Route as AuthenticatedDocenteCuentaRouteImport } from './routes/_authenticated/docente.cuenta'
import { Route as AuthenticatedDocenteComunidadRouteImport } from './routes/_authenticated/docente.comunidad'
import { Route as AuthenticatedDocenteClasesVivoRouteImport } from './routes/_authenticated/docente.clases-vivo'
import { Route as AuthenticatedDocenteCalificacionesRouteImport } from './routes/_authenticated/docente.calificaciones'
import { Route as AuthenticatedClaseVivoMeetingIdRouteImport } from './routes/_authenticated/clase-vivo.$meetingId'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminTestimoniosRouteImport } from './routes/_authenticated/admin.testimonios'
import { Route as AuthenticatedAdminSolicitudesRouteImport } from './routes/_authenticated/admin.solicitudes'
import { Route as AuthenticatedAdminProgramasRouteImport } from './routes/_authenticated/admin.programas'
import { Route as AuthenticatedAdminModulosRouteImport } from './routes/_authenticated/admin.modulos'
import { Route as AuthenticatedAdminMensajesRouteImport } from './routes/_authenticated/admin.mensajes'
import { Route as AuthenticatedAdminIntegracionesRouteImport } from './routes/_authenticated/admin.integraciones'
import { Route as AuthenticatedAdminInscripcionesRouteImport } from './routes/_authenticated/admin.inscripciones'
import { Route as AuthenticatedAdminHeroRouteImport } from './routes/_authenticated/admin.hero'
import { Route as AuthenticatedAdminGruposRouteImport } from './routes/_authenticated/admin.grupos'
import { Route as AuthenticatedAdminFacturacionRouteImport } from './routes/_authenticated/admin.facturacion'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/admin.eventos'
import { Route as AuthenticatedAdminEvaluacionesRouteImport } from './routes/_authenticated/admin.evaluaciones'
import { Route as AuthenticatedAdminDocentesRouteImport } from './routes/_authenticated/admin.docentes'
import { Route as AuthenticatedAdminCertificadosRouteImport } from './routes/_authenticated/admin.certificados'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin.categorias'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminAnunciosRouteImport } from './routes/_authenticated/admin.anuncios'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicRecordingMeetingIdRouteImport } from './routes/api/public/recording.$meetingId'
import { Route as ApiPublicHooksSyncActiveStudentsRouteImport } from './routes/api/public/hooks/sync-active-students'
import { Route as ApiPublicHooksReconcileZoomRecordingsRouteImport } from './routes/api/public/hooks/reconcile-zoom-recordings'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitudCursoRoute = SolicitudCursoRouteImport.update({
  id: '/solicitud-curso',
  path: '/solicitud-curso',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarPasswordRoute = RecuperarPasswordRouteImport.update({
  id: '/recuperar-password',
  path: '/recuperar-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasRoute = ProgramasRouteImport.update({
  id: '/programas',
  path: '/programas',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const DocentesRoute = DocentesRouteImport.update({
  id: '/docentes',
  path: '/docentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AccederRoute = AccederRouteImport.update({
  id: '/acceder',
  path: '/acceder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasIndexRoute = ProgramasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramasRoute,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificarNumeroRoute = VerificarNumeroRouteImport.update({
  id: '/verificar/$numero',
  path: '/verificar/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasSlugRoute = ProgramasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramasRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedEstudianteRoute = AuthenticatedEstudianteRouteImport.update({
  id: '/estudiante',
  path: '/estudiante',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocenteRoute = AuthenticatedDocenteRouteImport.update({
  id: '/docente',
  path: '/docente',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCertificadosRoute =
  AuthenticatedCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMisCursosIndexRoute =
  AuthenticatedMisCursosIndexRouteImport.update({
    id: '/mis-cursos/',
    path: '/mis-cursos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEstudianteIndexRoute =
  AuthenticatedEstudianteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEstudianteRoute,
  } as any)
const AuthenticatedDocenteIndexRoute =
  AuthenticatedDocenteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDocenteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicZoomWebhookRoute = ApiPublicZoomWebhookRouteImport.update({
  id: '/api/public/zoom-webhook',
  path: '/api/public/zoom-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCourseRequestRoute = ApiPublicCourseRequestRouteImport.update({
  id: '/api/public/course-request',
  path: '/api/public/course-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBalanceActivoWebhookRoute =
  ApiPublicBalanceActivoWebhookRouteImport.update({
    id: '/api/public/balance-activo-webhook',
    path: '/api/public/balance-activo-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMisCursosSlugRoute =
  AuthenticatedMisCursosSlugRouteImport.update({
    id: '/mis-cursos/$slug',
    path: '/mis-cursos/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEstudianteInstructivoRoute =
  AuthenticatedEstudianteInstructivoRouteImport.update({
    id: '/instructivo',
    path: '/instructivo',
    getParentRoute: () => AuthenticatedEstudianteRoute,
  } as any)
const AuthenticatedEstudianteFacturacionRoute =
  AuthenticatedEstudianteFacturacionRouteImport.update({
    id: '/facturacion',
    path: '/facturacion',
    getParentRoute: () => AuthenticatedEstudianteRoute,
  } as any)
const AuthenticatedEstudianteEvaluacionesRoute =
  AuthenticatedEstudianteEvaluacionesRouteImport.update({
    id: '/evaluaciones',
    path: '/evaluaciones',
    getParentRoute: () => AuthenticatedEstudianteRoute,
  } as any)
const AuthenticatedEstudianteCuentaRoute =
  AuthenticatedEstudianteCuentaRouteImport.update({
    id: '/cuenta',
    path: '/cuenta',
    getParentRoute: () => AuthenticatedEstudianteRoute,
  } as any)
const AuthenticatedDocenteLeccionesRoute =
  AuthenticatedDocenteLeccionesRouteImport.update({
    id: '/lecciones',
    path: '/lecciones',
    getParentRoute: () => AuthenticatedDocenteRoute,
  } as any)
const AuthenticatedDocenteInstructivoRoute =
  AuthenticatedDocenteInstructivoRouteImport.update({
    id: '/instructivo',
    path: '/instructivo',
    getParentRoute: () => AuthenticatedDocenteRoute,
  } as any)
const AuthenticatedDocenteGruposRoute =
  AuthenticatedDocenteGruposRouteImport.update({
    id: '/grupos',
    path: '/grupos',
    getParentRoute: () => AuthenticatedDocenteRoute,
  } as any)
const AuthenticatedDocenteEvaluacionesRoute =
  AuthenticatedDocenteEvaluacionesRouteImport.update({
    id: '/evaluaciones',
    path: '/evaluaciones',
    getParentRoute: () => AuthenticatedDocenteRoute,
  } as any)
const AuthenticatedDocenteCursosRoute =
  AuthenticatedDocenteCursosRouteImport.update({
    id: '/cursos',
    path: '/cursos',
    getParentRoute: () => AuthenticatedDocenteRoute,
  } as any)
const AuthenticatedDocenteCuentaRoute =
  AuthenticatedDocenteCuentaRouteImport.update({
    id: '/cuenta',
    path: '/cuenta',
    getParentRoute: () => AuthenticatedDocenteRoute,
  } as any)
const AuthenticatedDocenteComunidadRoute =
  AuthenticatedDocenteComunidadRouteImport.update({
    id: '/comunidad',
    path: '/comunidad',
    getParentRoute: () => AuthenticatedDocenteRoute,
  } as any)
const AuthenticatedDocenteClasesVivoRoute =
  AuthenticatedDocenteClasesVivoRouteImport.update({
    id: '/clases-vivo',
    path: '/clases-vivo',
    getParentRoute: () => AuthenticatedDocenteRoute,
  } as any)
const AuthenticatedDocenteCalificacionesRoute =
  AuthenticatedDocenteCalificacionesRouteImport.update({
    id: '/calificaciones',
    path: '/calificaciones',
    getParentRoute: () => AuthenticatedDocenteRoute,
  } as any)
const AuthenticatedClaseVivoMeetingIdRoute =
  AuthenticatedClaseVivoMeetingIdRouteImport.update({
    id: '/clase-vivo/$meetingId',
    path: '/clase-vivo/$meetingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTestimoniosRoute =
  AuthenticatedAdminTestimoniosRouteImport.update({
    id: '/testimonios',
    path: '/testimonios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSolicitudesRoute =
  AuthenticatedAdminSolicitudesRouteImport.update({
    id: '/solicitudes',
    path: '/solicitudes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProgramasRoute =
  AuthenticatedAdminProgramasRouteImport.update({
    id: '/programas',
    path: '/programas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModulosRoute =
  AuthenticatedAdminModulosRouteImport.update({
    id: '/modulos',
    path: '/modulos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMensajesRoute =
  AuthenticatedAdminMensajesRouteImport.update({
    id: '/mensajes',
    path: '/mensajes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntegracionesRoute =
  AuthenticatedAdminIntegracionesRouteImport.update({
    id: '/integraciones',
    path: '/integraciones',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInscripcionesRoute =
  AuthenticatedAdminInscripcionesRouteImport.update({
    id: '/inscripciones',
    path: '/inscripciones',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHeroRoute = AuthenticatedAdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminGruposRoute =
  AuthenticatedAdminGruposRouteImport.update({
    id: '/grupos',
    path: '/grupos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFacturacionRoute =
  AuthenticatedAdminFacturacionRouteImport.update({
    id: '/facturacion',
    path: '/facturacion',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEvaluacionesRoute =
  AuthenticatedAdminEvaluacionesRouteImport.update({
    id: '/evaluaciones',
    path: '/evaluaciones',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocentesRoute =
  AuthenticatedAdminDocentesRouteImport.update({
    id: '/docentes',
    path: '/docentes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCertificadosRoute =
  AuthenticatedAdminCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnunciosRoute =
  AuthenticatedAdminAnunciosRouteImport.update({
    id: '/anuncios',
    path: '/anuncios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRecordingMeetingIdRoute =
  ApiPublicRecordingMeetingIdRouteImport.update({
    id: '/api/public/recording/$meetingId',
    path: '/api/public/recording/$meetingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncActiveStudentsRoute =
  ApiPublicHooksSyncActiveStudentsRouteImport.update({
    id: '/api/public/hooks/sync-active-students',
    path: '/api/public/hooks/sync-active-students',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReconcileZoomRecordingsRoute =
  ApiPublicHooksReconcileZoomRecordingsRouteImport.update({
    id: '/api/public/hooks/reconcile-zoom-recordings',
    path: '/api/public/hooks/reconcile-zoom-recordings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceder': typeof AccederRoute
  '/blog': typeof BlogRouteWithChildren
  '/contactos': typeof ContactosRoute
  '/docentes': typeof DocentesRoute
  '/eventos': typeof EventosRoute
  '/galeria': typeof GaleriaRoute
  '/programas': typeof ProgramasRouteWithChildren
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/solicitud-curso': typeof SolicitudCursoRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/docente': typeof AuthenticatedDocenteRouteWithChildren
  '/estudiante': typeof AuthenticatedEstudianteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/programas/$slug': typeof ProgramasSlugRoute
  '/verificar/$numero': typeof VerificarNumeroRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/programas/': typeof ProgramasIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/certificados': typeof AuthenticatedAdminCertificadosRoute
  '/admin/docentes': typeof AuthenticatedAdminDocentesRoute
  '/admin/evaluaciones': typeof AuthenticatedAdminEvaluacionesRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/facturacion': typeof AuthenticatedAdminFacturacionRoute
  '/admin/grupos': typeof AuthenticatedAdminGruposRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/inscripciones': typeof AuthenticatedAdminInscripcionesRoute
  '/admin/integraciones': typeof AuthenticatedAdminIntegracionesRoute
  '/admin/mensajes': typeof AuthenticatedAdminMensajesRoute
  '/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/admin/programas': typeof AuthenticatedAdminProgramasRoute
  '/admin/solicitudes': typeof AuthenticatedAdminSolicitudesRoute
  '/admin/testimonios': typeof AuthenticatedAdminTestimoniosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/clase-vivo/$meetingId': typeof AuthenticatedClaseVivoMeetingIdRoute
  '/docente/calificaciones': typeof AuthenticatedDocenteCalificacionesRoute
  '/docente/clases-vivo': typeof AuthenticatedDocenteClasesVivoRoute
  '/docente/comunidad': typeof AuthenticatedDocenteComunidadRoute
  '/docente/cuenta': typeof AuthenticatedDocenteCuentaRoute
  '/docente/cursos': typeof AuthenticatedDocenteCursosRoute
  '/docente/evaluaciones': typeof AuthenticatedDocenteEvaluacionesRoute
  '/docente/grupos': typeof AuthenticatedDocenteGruposRoute
  '/docente/instructivo': typeof AuthenticatedDocenteInstructivoRoute
  '/docente/lecciones': typeof AuthenticatedDocenteLeccionesRoute
  '/estudiante/cuenta': typeof AuthenticatedEstudianteCuentaRoute
  '/estudiante/evaluaciones': typeof AuthenticatedEstudianteEvaluacionesRoute
  '/estudiante/facturacion': typeof AuthenticatedEstudianteFacturacionRoute
  '/estudiante/instructivo': typeof AuthenticatedEstudianteInstructivoRoute
  '/mis-cursos/$slug': typeof AuthenticatedMisCursosSlugRoute
  '/api/public/balance-activo-webhook': typeof ApiPublicBalanceActivoWebhookRoute
  '/api/public/course-request': typeof ApiPublicCourseRequestRoute
  '/api/public/zoom-webhook': typeof ApiPublicZoomWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/docente/': typeof AuthenticatedDocenteIndexRoute
  '/estudiante/': typeof AuthenticatedEstudianteIndexRoute
  '/mis-cursos/': typeof AuthenticatedMisCursosIndexRoute
  '/api/public/hooks/reconcile-zoom-recordings': typeof ApiPublicHooksReconcileZoomRecordingsRoute
  '/api/public/hooks/sync-active-students': typeof ApiPublicHooksSyncActiveStudentsRoute
  '/api/public/recording/$meetingId': typeof ApiPublicRecordingMeetingIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceder': typeof AccederRoute
  '/blog': typeof BlogRouteWithChildren
  '/contactos': typeof ContactosRoute
  '/docentes': typeof DocentesRoute
  '/eventos': typeof EventosRoute
  '/galeria': typeof GaleriaRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/solicitud-curso': typeof SolicitudCursoRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/programas/$slug': typeof ProgramasSlugRoute
  '/verificar/$numero': typeof VerificarNumeroRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/programas': typeof ProgramasIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/certificados': typeof AuthenticatedAdminCertificadosRoute
  '/admin/docentes': typeof AuthenticatedAdminDocentesRoute
  '/admin/evaluaciones': typeof AuthenticatedAdminEvaluacionesRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/facturacion': typeof AuthenticatedAdminFacturacionRoute
  '/admin/grupos': typeof AuthenticatedAdminGruposRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/inscripciones': typeof AuthenticatedAdminInscripcionesRoute
  '/admin/integraciones': typeof AuthenticatedAdminIntegracionesRoute
  '/admin/mensajes': typeof AuthenticatedAdminMensajesRoute
  '/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/admin/programas': typeof AuthenticatedAdminProgramasRoute
  '/admin/solicitudes': typeof AuthenticatedAdminSolicitudesRoute
  '/admin/testimonios': typeof AuthenticatedAdminTestimoniosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/clase-vivo/$meetingId': typeof AuthenticatedClaseVivoMeetingIdRoute
  '/docente/calificaciones': typeof AuthenticatedDocenteCalificacionesRoute
  '/docente/clases-vivo': typeof AuthenticatedDocenteClasesVivoRoute
  '/docente/comunidad': typeof AuthenticatedDocenteComunidadRoute
  '/docente/cuenta': typeof AuthenticatedDocenteCuentaRoute
  '/docente/cursos': typeof AuthenticatedDocenteCursosRoute
  '/docente/evaluaciones': typeof AuthenticatedDocenteEvaluacionesRoute
  '/docente/grupos': typeof AuthenticatedDocenteGruposRoute
  '/docente/instructivo': typeof AuthenticatedDocenteInstructivoRoute
  '/docente/lecciones': typeof AuthenticatedDocenteLeccionesRoute
  '/estudiante/cuenta': typeof AuthenticatedEstudianteCuentaRoute
  '/estudiante/evaluaciones': typeof AuthenticatedEstudianteEvaluacionesRoute
  '/estudiante/facturacion': typeof AuthenticatedEstudianteFacturacionRoute
  '/estudiante/instructivo': typeof AuthenticatedEstudianteInstructivoRoute
  '/mis-cursos/$slug': typeof AuthenticatedMisCursosSlugRoute
  '/api/public/balance-activo-webhook': typeof ApiPublicBalanceActivoWebhookRoute
  '/api/public/course-request': typeof ApiPublicCourseRequestRoute
  '/api/public/zoom-webhook': typeof ApiPublicZoomWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/docente': typeof AuthenticatedDocenteIndexRoute
  '/estudiante': typeof AuthenticatedEstudianteIndexRoute
  '/mis-cursos': typeof AuthenticatedMisCursosIndexRoute
  '/api/public/hooks/reconcile-zoom-recordings': typeof ApiPublicHooksReconcileZoomRecordingsRoute
  '/api/public/hooks/sync-active-students': typeof ApiPublicHooksSyncActiveStudentsRoute
  '/api/public/recording/$meetingId': typeof ApiPublicRecordingMeetingIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/acceder': typeof AccederRoute
  '/blog': typeof BlogRouteWithChildren
  '/contactos': typeof ContactosRoute
  '/docentes': typeof DocentesRoute
  '/eventos': typeof EventosRoute
  '/galeria': typeof GaleriaRoute
  '/programas': typeof ProgramasRouteWithChildren
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/solicitud-curso': typeof SolicitudCursoRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/certificados': typeof AuthenticatedCertificadosRoute
  '/_authenticated/docente': typeof AuthenticatedDocenteRouteWithChildren
  '/_authenticated/estudiante': typeof AuthenticatedEstudianteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/programas/$slug': typeof ProgramasSlugRoute
  '/verificar/$numero': typeof VerificarNumeroRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/programas/': typeof ProgramasIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/certificados': typeof AuthenticatedAdminCertificadosRoute
  '/_authenticated/admin/docentes': typeof AuthenticatedAdminDocentesRoute
  '/_authenticated/admin/evaluaciones': typeof AuthenticatedAdminEvaluacionesRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/_authenticated/admin/facturacion': typeof AuthenticatedAdminFacturacionRoute
  '/_authenticated/admin/grupos': typeof AuthenticatedAdminGruposRoute
  '/_authenticated/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/_authenticated/admin/inscripciones': typeof AuthenticatedAdminInscripcionesRoute
  '/_authenticated/admin/integraciones': typeof AuthenticatedAdminIntegracionesRoute
  '/_authenticated/admin/mensajes': typeof AuthenticatedAdminMensajesRoute
  '/_authenticated/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/_authenticated/admin/programas': typeof AuthenticatedAdminProgramasRoute
  '/_authenticated/admin/solicitudes': typeof AuthenticatedAdminSolicitudesRoute
  '/_authenticated/admin/testimonios': typeof AuthenticatedAdminTestimoniosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/clase-vivo/$meetingId': typeof AuthenticatedClaseVivoMeetingIdRoute
  '/_authenticated/docente/calificaciones': typeof AuthenticatedDocenteCalificacionesRoute
  '/_authenticated/docente/clases-vivo': typeof AuthenticatedDocenteClasesVivoRoute
  '/_authenticated/docente/comunidad': typeof AuthenticatedDocenteComunidadRoute
  '/_authenticated/docente/cuenta': typeof AuthenticatedDocenteCuentaRoute
  '/_authenticated/docente/cursos': typeof AuthenticatedDocenteCursosRoute
  '/_authenticated/docente/evaluaciones': typeof AuthenticatedDocenteEvaluacionesRoute
  '/_authenticated/docente/grupos': typeof AuthenticatedDocenteGruposRoute
  '/_authenticated/docente/instructivo': typeof AuthenticatedDocenteInstructivoRoute
  '/_authenticated/docente/lecciones': typeof AuthenticatedDocenteLeccionesRoute
  '/_authenticated/estudiante/cuenta': typeof AuthenticatedEstudianteCuentaRoute
  '/_authenticated/estudiante/evaluaciones': typeof AuthenticatedEstudianteEvaluacionesRoute
  '/_authenticated/estudiante/facturacion': typeof AuthenticatedEstudianteFacturacionRoute
  '/_authenticated/estudiante/instructivo': typeof AuthenticatedEstudianteInstructivoRoute
  '/_authenticated/mis-cursos/$slug': typeof AuthenticatedMisCursosSlugRoute
  '/api/public/balance-activo-webhook': typeof ApiPublicBalanceActivoWebhookRoute
  '/api/public/course-request': typeof ApiPublicCourseRequestRoute
  '/api/public/zoom-webhook': typeof ApiPublicZoomWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/docente/': typeof AuthenticatedDocenteIndexRoute
  '/_authenticated/estudiante/': typeof AuthenticatedEstudianteIndexRoute
  '/_authenticated/mis-cursos/': typeof AuthenticatedMisCursosIndexRoute
  '/api/public/hooks/reconcile-zoom-recordings': typeof ApiPublicHooksReconcileZoomRecordingsRoute
  '/api/public/hooks/sync-active-students': typeof ApiPublicHooksSyncActiveStudentsRoute
  '/api/public/recording/$meetingId': typeof ApiPublicRecordingMeetingIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceder'
    | '/blog'
    | '/contactos'
    | '/docentes'
    | '/eventos'
    | '/galeria'
    | '/programas'
    | '/recuperar-password'
    | '/registro'
    | '/reset-password'
    | '/sobre-nosotros'
    | '/solicitud-curso'
    | '/unsubscribe'
    | '/admin'
    | '/certificados'
    | '/docente'
    | '/estudiante'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/programas/$slug'
    | '/verificar/$numero'
    | '/verify/$code'
    | '/programas/'
    | '/.lovable/oauth/consent'
    | '/admin/anuncios'
    | '/admin/blog'
    | '/admin/categorias'
    | '/admin/certificados'
    | '/admin/docentes'
    | '/admin/evaluaciones'
    | '/admin/eventos'
    | '/admin/facturacion'
    | '/admin/grupos'
    | '/admin/hero'
    | '/admin/inscripciones'
    | '/admin/integraciones'
    | '/admin/mensajes'
    | '/admin/modulos'
    | '/admin/programas'
    | '/admin/solicitudes'
    | '/admin/testimonios'
    | '/admin/usuarios'
    | '/clase-vivo/$meetingId'
    | '/docente/calificaciones'
    | '/docente/clases-vivo'
    | '/docente/comunidad'
    | '/docente/cuenta'
    | '/docente/cursos'
    | '/docente/evaluaciones'
    | '/docente/grupos'
    | '/docente/instructivo'
    | '/docente/lecciones'
    | '/estudiante/cuenta'
    | '/estudiante/evaluaciones'
    | '/estudiante/facturacion'
    | '/estudiante/instructivo'
    | '/mis-cursos/$slug'
    | '/api/public/balance-activo-webhook'
    | '/api/public/course-request'
    | '/api/public/zoom-webhook'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/docente/'
    | '/estudiante/'
    | '/mis-cursos/'
    | '/api/public/hooks/reconcile-zoom-recordings'
    | '/api/public/hooks/sync-active-students'
    | '/api/public/recording/$meetingId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceder'
    | '/blog'
    | '/contactos'
    | '/docentes'
    | '/eventos'
    | '/galeria'
    | '/recuperar-password'
    | '/registro'
    | '/reset-password'
    | '/sobre-nosotros'
    | '/solicitud-curso'
    | '/unsubscribe'
    | '/certificados'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/programas/$slug'
    | '/verificar/$numero'
    | '/verify/$code'
    | '/programas'
    | '/.lovable/oauth/consent'
    | '/admin/anuncios'
    | '/admin/blog'
    | '/admin/categorias'
    | '/admin/certificados'
    | '/admin/docentes'
    | '/admin/evaluaciones'
    | '/admin/eventos'
    | '/admin/facturacion'
    | '/admin/grupos'
    | '/admin/hero'
    | '/admin/inscripciones'
    | '/admin/integraciones'
    | '/admin/mensajes'
    | '/admin/modulos'
    | '/admin/programas'
    | '/admin/solicitudes'
    | '/admin/testimonios'
    | '/admin/usuarios'
    | '/clase-vivo/$meetingId'
    | '/docente/calificaciones'
    | '/docente/clases-vivo'
    | '/docente/comunidad'
    | '/docente/cuenta'
    | '/docente/cursos'
    | '/docente/evaluaciones'
    | '/docente/grupos'
    | '/docente/instructivo'
    | '/docente/lecciones'
    | '/estudiante/cuenta'
    | '/estudiante/evaluaciones'
    | '/estudiante/facturacion'
    | '/estudiante/instructivo'
    | '/mis-cursos/$slug'
    | '/api/public/balance-activo-webhook'
    | '/api/public/course-request'
    | '/api/public/zoom-webhook'
    | '/lovable/email/suppression'
    | '/admin'
    | '/docente'
    | '/estudiante'
    | '/mis-cursos'
    | '/api/public/hooks/reconcile-zoom-recordings'
    | '/api/public/hooks/sync-active-students'
    | '/api/public/recording/$meetingId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acceder'
    | '/blog'
    | '/contactos'
    | '/docentes'
    | '/eventos'
    | '/galeria'
    | '/programas'
    | '/recuperar-password'
    | '/registro'
    | '/reset-password'
    | '/sobre-nosotros'
    | '/solicitud-curso'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/certificados'
    | '/_authenticated/docente'
    | '/_authenticated/estudiante'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/programas/$slug'
    | '/verificar/$numero'
    | '/verify/$code'
    | '/programas/'
    | '/.lovable/oauth/consent'
    | '/_authenticated/admin/anuncios'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/certificados'
    | '/_authenticated/admin/docentes'
    | '/_authenticated/admin/evaluaciones'
    | '/_authenticated/admin/eventos'
    | '/_authenticated/admin/facturacion'
    | '/_authenticated/admin/grupos'
    | '/_authenticated/admin/hero'
    | '/_authenticated/admin/inscripciones'
    | '/_authenticated/admin/integraciones'
    | '/_authenticated/admin/mensajes'
    | '/_authenticated/admin/modulos'
    | '/_authenticated/admin/programas'
    | '/_authenticated/admin/solicitudes'
    | '/_authenticated/admin/testimonios'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/clase-vivo/$meetingId'
    | '/_authenticated/docente/calificaciones'
    | '/_authenticated/docente/clases-vivo'
    | '/_authenticated/docente/comunidad'
    | '/_authenticated/docente/cuenta'
    | '/_authenticated/docente/cursos'
    | '/_authenticated/docente/evaluaciones'
    | '/_authenticated/docente/grupos'
    | '/_authenticated/docente/instructivo'
    | '/_authenticated/docente/lecciones'
    | '/_authenticated/estudiante/cuenta'
    | '/_authenticated/estudiante/evaluaciones'
    | '/_authenticated/estudiante/facturacion'
    | '/_authenticated/estudiante/instructivo'
    | '/_authenticated/mis-cursos/$slug'
    | '/api/public/balance-activo-webhook'
    | '/api/public/course-request'
    | '/api/public/zoom-webhook'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/_authenticated/docente/'
    | '/_authenticated/estudiante/'
    | '/_authenticated/mis-cursos/'
    | '/api/public/hooks/reconcile-zoom-recordings'
    | '/api/public/hooks/sync-active-students'
    | '/api/public/recording/$meetingId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AccederRoute: typeof AccederRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactosRoute: typeof ContactosRoute
  DocentesRoute: typeof DocentesRoute
  EventosRoute: typeof EventosRoute
  GaleriaRoute: typeof GaleriaRoute
  ProgramasRoute: typeof ProgramasRouteWithChildren
  RecuperarPasswordRoute: typeof RecuperarPasswordRoute
  RegistroRoute: typeof RegistroRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  SolicitudCursoRoute: typeof SolicitudCursoRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  VerificarNumeroRoute: typeof VerificarNumeroRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicBalanceActivoWebhookRoute: typeof ApiPublicBalanceActivoWebhookRoute
  ApiPublicCourseRequestRoute: typeof ApiPublicCourseRequestRoute
  ApiPublicZoomWebhookRoute: typeof ApiPublicZoomWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksReconcileZoomRecordingsRoute: typeof ApiPublicHooksReconcileZoomRecordingsRoute
  ApiPublicHooksSyncActiveStudentsRoute: typeof ApiPublicHooksSyncActiveStudentsRoute
  ApiPublicRecordingMeetingIdRoute: typeof ApiPublicRecordingMeetingIdRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitud-curso': {
      id: '/solicitud-curso'
      path: '/solicitud-curso'
      fullPath: '/solicitud-curso'
      preLoaderRoute: typeof SolicitudCursoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-password': {
      id: '/recuperar-password'
      path: '/recuperar-password'
      fullPath: '/recuperar-password'
      preLoaderRoute: typeof RecuperarPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas': {
      id: '/programas'
      path: '/programas'
      fullPath: '/programas'
      preLoaderRoute: typeof ProgramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docentes': {
      id: '/docentes'
      path: '/docentes'
      fullPath: '/docentes'
      preLoaderRoute: typeof DocentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceder': {
      id: '/acceder'
      path: '/acceder'
      fullPath: '/acceder'
      preLoaderRoute: typeof AccederRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas/': {
      id: '/programas/'
      path: '/'
      fullPath: '/programas/'
      preLoaderRoute: typeof ProgramasIndexRouteImport
      parentRoute: typeof ProgramasRoute
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificar/$numero': {
      id: '/verificar/$numero'
      path: '/verificar/$numero'
      fullPath: '/verificar/$numero'
      preLoaderRoute: typeof VerificarNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas/$slug': {
      id: '/programas/$slug'
      path: '/$slug'
      fullPath: '/programas/$slug'
      preLoaderRoute: typeof ProgramasSlugRouteImport
      parentRoute: typeof ProgramasRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/estudiante': {
      id: '/_authenticated/estudiante'
      path: '/estudiante'
      fullPath: '/estudiante'
      preLoaderRoute: typeof AuthenticatedEstudianteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/docente': {
      id: '/_authenticated/docente'
      path: '/docente'
      fullPath: '/docente'
      preLoaderRoute: typeof AuthenticatedDocenteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/certificados': {
      id: '/_authenticated/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof AuthenticatedCertificadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mis-cursos/': {
      id: '/_authenticated/mis-cursos/'
      path: '/mis-cursos'
      fullPath: '/mis-cursos/'
      preLoaderRoute: typeof AuthenticatedMisCursosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estudiante/': {
      id: '/_authenticated/estudiante/'
      path: '/'
      fullPath: '/estudiante/'
      preLoaderRoute: typeof AuthenticatedEstudianteIndexRouteImport
      parentRoute: typeof AuthenticatedEstudianteRoute
    }
    '/_authenticated/docente/': {
      id: '/_authenticated/docente/'
      path: '/'
      fullPath: '/docente/'
      preLoaderRoute: typeof AuthenticatedDocenteIndexRouteImport
      parentRoute: typeof AuthenticatedDocenteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zoom-webhook': {
      id: '/api/public/zoom-webhook'
      path: '/api/public/zoom-webhook'
      fullPath: '/api/public/zoom-webhook'
      preLoaderRoute: typeof ApiPublicZoomWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/course-request': {
      id: '/api/public/course-request'
      path: '/api/public/course-request'
      fullPath: '/api/public/course-request'
      preLoaderRoute: typeof ApiPublicCourseRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/balance-activo-webhook': {
      id: '/api/public/balance-activo-webhook'
      path: '/api/public/balance-activo-webhook'
      fullPath: '/api/public/balance-activo-webhook'
      preLoaderRoute: typeof ApiPublicBalanceActivoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mis-cursos/$slug': {
      id: '/_authenticated/mis-cursos/$slug'
      path: '/mis-cursos/$slug'
      fullPath: '/mis-cursos/$slug'
      preLoaderRoute: typeof AuthenticatedMisCursosSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estudiante/instructivo': {
      id: '/_authenticated/estudiante/instructivo'
      path: '/instructivo'
      fullPath: '/estudiante/instructivo'
      preLoaderRoute: typeof AuthenticatedEstudianteInstructivoRouteImport
      parentRoute: typeof AuthenticatedEstudianteRoute
    }
    '/_authenticated/estudiante/facturacion': {
      id: '/_authenticated/estudiante/facturacion'
      path: '/facturacion'
      fullPath: '/estudiante/facturacion'
      preLoaderRoute: typeof AuthenticatedEstudianteFacturacionRouteImport
      parentRoute: typeof AuthenticatedEstudianteRoute
    }
    '/_authenticated/estudiante/evaluaciones': {
      id: '/_authenticated/estudiante/evaluaciones'
      path: '/evaluaciones'
      fullPath: '/estudiante/evaluaciones'
      preLoaderRoute: typeof AuthenticatedEstudianteEvaluacionesRouteImport
      parentRoute: typeof AuthenticatedEstudianteRoute
    }
    '/_authenticated/estudiante/cuenta': {
      id: '/_authenticated/estudiante/cuenta'
      path: '/cuenta'
      fullPath: '/estudiante/cuenta'
      preLoaderRoute: typeof AuthenticatedEstudianteCuentaRouteImport
      parentRoute: typeof AuthenticatedEstudianteRoute
    }
    '/_authenticated/docente/lecciones': {
      id: '/_authenticated/docente/lecciones'
      path: '/lecciones'
      fullPath: '/docente/lecciones'
      preLoaderRoute: typeof AuthenticatedDocenteLeccionesRouteImport
      parentRoute: typeof AuthenticatedDocenteRoute
    }
    '/_authenticated/docente/instructivo': {
      id: '/_authenticated/docente/instructivo'
      path: '/instructivo'
      fullPath: '/docente/instructivo'
      preLoaderRoute: typeof AuthenticatedDocenteInstructivoRouteImport
      parentRoute: typeof AuthenticatedDocenteRoute
    }
    '/_authenticated/docente/grupos': {
      id: '/_authenticated/docente/grupos'
      path: '/grupos'
      fullPath: '/docente/grupos'
      preLoaderRoute: typeof AuthenticatedDocenteGruposRouteImport
      parentRoute: typeof AuthenticatedDocenteRoute
    }
    '/_authenticated/docente/evaluaciones': {
      id: '/_authenticated/docente/evaluaciones'
      path: '/evaluaciones'
      fullPath: '/docente/evaluaciones'
      preLoaderRoute: typeof AuthenticatedDocenteEvaluacionesRouteImport
      parentRoute: typeof AuthenticatedDocenteRoute
    }
    '/_authenticated/docente/cursos': {
      id: '/_authenticated/docente/cursos'
      path: '/cursos'
      fullPath: '/docente/cursos'
      preLoaderRoute: typeof AuthenticatedDocenteCursosRouteImport
      parentRoute: typeof AuthenticatedDocenteRoute
    }
    '/_authenticated/docente/cuenta': {
      id: '/_authenticated/docente/cuenta'
      path: '/cuenta'
      fullPath: '/docente/cuenta'
      preLoaderRoute: typeof AuthenticatedDocenteCuentaRouteImport
      parentRoute: typeof AuthenticatedDocenteRoute
    }
    '/_authenticated/docente/comunidad': {
      id: '/_authenticated/docente/comunidad'
      path: '/comunidad'
      fullPath: '/docente/comunidad'
      preLoaderRoute: typeof AuthenticatedDocenteComunidadRouteImport
      parentRoute: typeof AuthenticatedDocenteRoute
    }
    '/_authenticated/docente/clases-vivo': {
      id: '/_authenticated/docente/clases-vivo'
      path: '/clases-vivo'
      fullPath: '/docente/clases-vivo'
      preLoaderRoute: typeof AuthenticatedDocenteClasesVivoRouteImport
      parentRoute: typeof AuthenticatedDocenteRoute
    }
    '/_authenticated/docente/calificaciones': {
      id: '/_authenticated/docente/calificaciones'
      path: '/calificaciones'
      fullPath: '/docente/calificaciones'
      preLoaderRoute: typeof AuthenticatedDocenteCalificacionesRouteImport
      parentRoute: typeof AuthenticatedDocenteRoute
    }
    '/_authenticated/clase-vivo/$meetingId': {
      id: '/_authenticated/clase-vivo/$meetingId'
      path: '/clase-vivo/$meetingId'
      fullPath: '/clase-vivo/$meetingId'
      preLoaderRoute: typeof AuthenticatedClaseVivoMeetingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/testimonios': {
      id: '/_authenticated/admin/testimonios'
      path: '/testimonios'
      fullPath: '/admin/testimonios'
      preLoaderRoute: typeof AuthenticatedAdminTestimoniosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/solicitudes': {
      id: '/_authenticated/admin/solicitudes'
      path: '/solicitudes'
      fullPath: '/admin/solicitudes'
      preLoaderRoute: typeof AuthenticatedAdminSolicitudesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/programas': {
      id: '/_authenticated/admin/programas'
      path: '/programas'
      fullPath: '/admin/programas'
      preLoaderRoute: typeof AuthenticatedAdminProgramasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/modulos': {
      id: '/_authenticated/admin/modulos'
      path: '/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AuthenticatedAdminModulosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mensajes': {
      id: '/_authenticated/admin/mensajes'
      path: '/mensajes'
      fullPath: '/admin/mensajes'
      preLoaderRoute: typeof AuthenticatedAdminMensajesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/integraciones': {
      id: '/_authenticated/admin/integraciones'
      path: '/integraciones'
      fullPath: '/admin/integraciones'
      preLoaderRoute: typeof AuthenticatedAdminIntegracionesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inscripciones': {
      id: '/_authenticated/admin/inscripciones'
      path: '/inscripciones'
      fullPath: '/admin/inscripciones'
      preLoaderRoute: typeof AuthenticatedAdminInscripcionesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hero': {
      id: '/_authenticated/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AuthenticatedAdminHeroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/grupos': {
      id: '/_authenticated/admin/grupos'
      path: '/grupos'
      fullPath: '/admin/grupos'
      preLoaderRoute: typeof AuthenticatedAdminGruposRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/facturacion': {
      id: '/_authenticated/admin/facturacion'
      path: '/facturacion'
      fullPath: '/admin/facturacion'
      preLoaderRoute: typeof AuthenticatedAdminFacturacionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/evaluaciones': {
      id: '/_authenticated/admin/evaluaciones'
      path: '/evaluaciones'
      fullPath: '/admin/evaluaciones'
      preLoaderRoute: typeof AuthenticatedAdminEvaluacionesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/docentes': {
      id: '/_authenticated/admin/docentes'
      path: '/docentes'
      fullPath: '/admin/docentes'
      preLoaderRoute: typeof AuthenticatedAdminDocentesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/certificados': {
      id: '/_authenticated/admin/certificados'
      path: '/certificados'
      fullPath: '/admin/certificados'
      preLoaderRoute: typeof AuthenticatedAdminCertificadosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/anuncios': {
      id: '/_authenticated/admin/anuncios'
      path: '/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AuthenticatedAdminAnunciosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/recording/$meetingId': {
      id: '/api/public/recording/$meetingId'
      path: '/api/public/recording/$meetingId'
      fullPath: '/api/public/recording/$meetingId'
      preLoaderRoute: typeof ApiPublicRecordingMeetingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-active-students': {
      id: '/api/public/hooks/sync-active-students'
      path: '/api/public/hooks/sync-active-students'
      fullPath: '/api/public/hooks/sync-active-students'
      preLoaderRoute: typeof ApiPublicHooksSyncActiveStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reconcile-zoom-recordings': {
      id: '/api/public/hooks/reconcile-zoom-recordings'
      path: '/api/public/hooks/reconcile-zoom-recordings'
      fullPath: '/api/public/hooks/reconcile-zoom-recordings'
      preLoaderRoute: typeof ApiPublicHooksReconcileZoomRecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnunciosRoute: typeof AuthenticatedAdminAnunciosRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminCertificadosRoute: typeof AuthenticatedAdminCertificadosRoute
  AuthenticatedAdminDocentesRoute: typeof AuthenticatedAdminDocentesRoute
  AuthenticatedAdminEvaluacionesRoute: typeof AuthenticatedAdminEvaluacionesRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
  AuthenticatedAdminFacturacionRoute: typeof AuthenticatedAdminFacturacionRoute
  AuthenticatedAdminGruposRoute: typeof AuthenticatedAdminGruposRoute
  AuthenticatedAdminHeroRoute: typeof AuthenticatedAdminHeroRoute
  AuthenticatedAdminInscripcionesRoute: typeof AuthenticatedAdminInscripcionesRoute
  AuthenticatedAdminIntegracionesRoute: typeof AuthenticatedAdminIntegracionesRoute
  AuthenticatedAdminMensajesRoute: typeof AuthenticatedAdminMensajesRoute
  AuthenticatedAdminModulosRoute: typeof AuthenticatedAdminModulosRoute
  AuthenticatedAdminProgramasRoute: typeof AuthenticatedAdminProgramasRoute
  AuthenticatedAdminSolicitudesRoute: typeof AuthenticatedAdminSolicitudesRoute
  AuthenticatedAdminTestimoniosRoute: typeof AuthenticatedAdminTestimoniosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnunciosRoute: AuthenticatedAdminAnunciosRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminCertificadosRoute: AuthenticatedAdminCertificadosRoute,
  AuthenticatedAdminDocentesRoute: AuthenticatedAdminDocentesRoute,
  AuthenticatedAdminEvaluacionesRoute: AuthenticatedAdminEvaluacionesRoute,
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
  AuthenticatedAdminFacturacionRoute: AuthenticatedAdminFacturacionRoute,
  AuthenticatedAdminGruposRoute: AuthenticatedAdminGruposRoute,
  AuthenticatedAdminHeroRoute: AuthenticatedAdminHeroRoute,
  AuthenticatedAdminInscripcionesRoute: AuthenticatedAdminInscripcionesRoute,
  AuthenticatedAdminIntegracionesRoute: AuthenticatedAdminIntegracionesRoute,
  AuthenticatedAdminMensajesRoute: AuthenticatedAdminMensajesRoute,
  AuthenticatedAdminModulosRoute: AuthenticatedAdminModulosRoute,
  AuthenticatedAdminProgramasRoute: AuthenticatedAdminProgramasRoute,
  AuthenticatedAdminSolicitudesRoute: AuthenticatedAdminSolicitudesRoute,
  AuthenticatedAdminTestimoniosRoute: AuthenticatedAdminTestimoniosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDocenteRouteChildren {
  AuthenticatedDocenteCalificacionesRoute: typeof AuthenticatedDocenteCalificacionesRoute
  AuthenticatedDocenteClasesVivoRoute: typeof AuthenticatedDocenteClasesVivoRoute
  AuthenticatedDocenteComunidadRoute: typeof AuthenticatedDocenteComunidadRoute
  AuthenticatedDocenteCuentaRoute: typeof AuthenticatedDocenteCuentaRoute
  AuthenticatedDocenteCursosRoute: typeof AuthenticatedDocenteCursosRoute
  AuthenticatedDocenteEvaluacionesRoute: typeof AuthenticatedDocenteEvaluacionesRoute
  AuthenticatedDocenteGruposRoute: typeof AuthenticatedDocenteGruposRoute
  AuthenticatedDocenteInstructivoRoute: typeof AuthenticatedDocenteInstructivoRoute
  AuthenticatedDocenteLeccionesRoute: typeof AuthenticatedDocenteLeccionesRoute
  AuthenticatedDocenteIndexRoute: typeof AuthenticatedDocenteIndexRoute
}

const AuthenticatedDocenteRouteChildren: AuthenticatedDocenteRouteChildren = {
  AuthenticatedDocenteCalificacionesRoute:
    AuthenticatedDocenteCalificacionesRoute,
  AuthenticatedDocenteClasesVivoRoute: AuthenticatedDocenteClasesVivoRoute,
  AuthenticatedDocenteComunidadRoute: AuthenticatedDocenteComunidadRoute,
  AuthenticatedDocenteCuentaRoute: AuthenticatedDocenteCuentaRoute,
  AuthenticatedDocenteCursosRoute: AuthenticatedDocenteCursosRoute,
  AuthenticatedDocenteEvaluacionesRoute: AuthenticatedDocenteEvaluacionesRoute,
  AuthenticatedDocenteGruposRoute: AuthenticatedDocenteGruposRoute,
  AuthenticatedDocenteInstructivoRoute: AuthenticatedDocenteInstructivoRoute,
  AuthenticatedDocenteLeccionesRoute: AuthenticatedDocenteLeccionesRoute,
  AuthenticatedDocenteIndexRoute: AuthenticatedDocenteIndexRoute,
}

const AuthenticatedDocenteRouteWithChildren =
  AuthenticatedDocenteRoute._addFileChildren(AuthenticatedDocenteRouteChildren)

interface AuthenticatedEstudianteRouteChildren {
  AuthenticatedEstudianteCuentaRoute: typeof AuthenticatedEstudianteCuentaRoute
  AuthenticatedEstudianteEvaluacionesRoute: typeof AuthenticatedEstudianteEvaluacionesRoute
  AuthenticatedEstudianteFacturacionRoute: typeof AuthenticatedEstudianteFacturacionRoute
  AuthenticatedEstudianteInstructivoRoute: typeof AuthenticatedEstudianteInstructivoRoute
  AuthenticatedEstudianteIndexRoute: typeof AuthenticatedEstudianteIndexRoute
}

const AuthenticatedEstudianteRouteChildren: AuthenticatedEstudianteRouteChildren =
  {
    AuthenticatedEstudianteCuentaRoute: AuthenticatedEstudianteCuentaRoute,
    AuthenticatedEstudianteEvaluacionesRoute:
      AuthenticatedEstudianteEvaluacionesRoute,
    AuthenticatedEstudianteFacturacionRoute:
      AuthenticatedEstudianteFacturacionRoute,
    AuthenticatedEstudianteInstructivoRoute:
      AuthenticatedEstudianteInstructivoRoute,
    AuthenticatedEstudianteIndexRoute: AuthenticatedEstudianteIndexRoute,
  }

const AuthenticatedEstudianteRouteWithChildren =
  AuthenticatedEstudianteRoute._addFileChildren(
    AuthenticatedEstudianteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCertificadosRoute: typeof AuthenticatedCertificadosRoute
  AuthenticatedDocenteRoute: typeof AuthenticatedDocenteRouteWithChildren
  AuthenticatedEstudianteRoute: typeof AuthenticatedEstudianteRouteWithChildren
  AuthenticatedClaseVivoMeetingIdRoute: typeof AuthenticatedClaseVivoMeetingIdRoute
  AuthenticatedMisCursosSlugRoute: typeof AuthenticatedMisCursosSlugRoute
  AuthenticatedMisCursosIndexRoute: typeof AuthenticatedMisCursosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCertificadosRoute: AuthenticatedCertificadosRoute,
  AuthenticatedDocenteRoute: AuthenticatedDocenteRouteWithChildren,
  AuthenticatedEstudianteRoute: AuthenticatedEstudianteRouteWithChildren,
  AuthenticatedClaseVivoMeetingIdRoute: AuthenticatedClaseVivoMeetingIdRoute,
  AuthenticatedMisCursosSlugRoute: AuthenticatedMisCursosSlugRoute,
  AuthenticatedMisCursosIndexRoute: AuthenticatedMisCursosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ProgramasRouteChildren {
  ProgramasSlugRoute: typeof ProgramasSlugRoute
  ProgramasIndexRoute: typeof ProgramasIndexRoute
}

const ProgramasRouteChildren: ProgramasRouteChildren = {
  ProgramasSlugRoute: ProgramasSlugRoute,
  ProgramasIndexRoute: ProgramasIndexRoute,
}

const ProgramasRouteWithChildren = ProgramasRoute._addFileChildren(
  ProgramasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AccederRoute: AccederRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactosRoute: ContactosRoute,
  DocentesRoute: DocentesRoute,
  EventosRoute: EventosRoute,
  GaleriaRoute: GaleriaRoute,
  ProgramasRoute: ProgramasRouteWithChildren,
  RecuperarPasswordRoute: RecuperarPasswordRoute,
  RegistroRoute: RegistroRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  SolicitudCursoRoute: SolicitudCursoRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  VerificarNumeroRoute: VerificarNumeroRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicBalanceActivoWebhookRoute: ApiPublicBalanceActivoWebhookRoute,
  ApiPublicCourseRequestRoute: ApiPublicCourseRequestRoute,
  ApiPublicZoomWebhookRoute: ApiPublicZoomWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksReconcileZoomRecordingsRoute:
    ApiPublicHooksReconcileZoomRecordingsRoute,
  ApiPublicHooksSyncActiveStudentsRoute: ApiPublicHooksSyncActiveStudentsRoute,
  ApiPublicRecordingMeetingIdRoute: ApiPublicRecordingMeetingIdRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
